var w=viewportSize.getWidth(),h=viewportSize.getHeight(),w=Number(w),h=Number(h),pageCount=1,city="",category="",topic="",loadMore=1,pckry="",$container="",filterData="",container=document.querySelector(".main-container"),selectDefaultFilter=".home",postAction="",topicId="",preAction="",preUrl="https://in.explara.com",eventId="",requiredLogin=!1,accurl="",exchangePage=!1,pageUrl=window.location.href,tempSub=pageUrl.split("?"),pageFromReq="",mainWebUrl="",countrySearch="",pageUrl=tempSub[0];
$(document).ready(function(){$(".bottom-bar .bottom-bar-hearts div").click(function(){$(this).hasClass("unchecked")?($(this).addClass("icon-heart1").removeClass("icon-heart2").removeClass("unchecked").addClass("checked"),$(this).parents(".item").removeClass("unchecked").addClass("checked")):$(this).hasClass("checked")&&($(this).addClass("icon-heart2").removeClass("icon-heart1").removeClass("checked").addClass("unchecked"),$(this).parents(".item").removeClass("checked").addClass("unchecked"))});$(".bottom-section #heart4 div").click(function(){$(this).parent().hasClass("unchecked")?
($(this).parent().addClass("checked").removeClass("unchecked"),$(this).removeClass("icon-gheart").addClass("icon-heart")):$(this).parent().hasClass("checked")&&($(this).parent().addClass("unchecked").removeClass("checked"),$(this).removeClass("icon-heart").addClass("icon-gheart"))});$(".bottom-section #heart2 div").click(function(){$(this).parent().hasClass("unchecked")?($(this).parent().addClass("checked").removeClass("unchecked"),$(this).removeClass("icon-gheart").addClass("icon-heart")):$(this).parent().hasClass("checked")&&
($(this).parent().addClass("unchecked").removeClass("checked"),$(this).removeClass("icon-heart").addClass("icon-gheart"))});768<=w&&($(".section_2 #topics .topic .follow-btn").mouseenter(function(){$(this).parent().hasClass("follow")&&$(this).children().removeClass("icon-follow-check").html("unfollow").css({top:"0"})}),$(".section_2 #topics .topic .follow-btn").mouseleave(function(){$(this).parent().hasClass("follow")&&$(this).children().addClass("icon-follow-check").empty().css({top:"7px"})}));$("#loggedInUser").click(function(a){login()});
$("#signupUser").click(function(a){signUp()});$("#forgotUser").click(function(a){forgot()});$("#banner-content .tags .item").click(function(){$(this).hasClass("unselected")?($(this).removeClass("unselected").addClass("selected"),$(this).children(".image").removeClass("icon-circle").addClass("icon-tick")):$(this).hasClass("selected")});860<=w&&992>w&&$("#main-search").attr({placeholder:"Search"});$("#menu_icon").click(function(){$("#search_icon").hasClass("icon-close_40")&&($("#search_icon").addClass("icon-search_40").removeClass("icon-close_40"),
$("#small-device-search").fadeOut(250).removeClass("active_search"),$("body").removeClass("active_menu_body"));$("#small-device-menu").hasClass("active_menu")||($("#small-device-menu").show("slide",{direction:"left"},250).addClass("active_menu"),$("#small-device-menu-overlay").fadeIn(500),$("body").addClass("active_menu_body"),$("#menu_icon").hasClass("icon-menu_40")&&($("#menu_icon").hide(),$("#menu_close_button").show()))});$("#menu_close_button").click(function(){$("#small-device-menu").hasClass("active_menu")&&
($("#small-device-menu").hide("slide",{direction:"left"},250).removeClass("active_menu"),$("#small-device-menu-overlay").fadeOut(500),$("body").removeClass("active_menu_body"),$("#menu_close_button").hasClass("icon-close_40")&&($("#menu_close_button").hide(),$("#menu_icon").show()))});$("#small-device-menu-overlay").click(function(){$("#small-device-menu").hasClass("active_menu")&&($("#small-device-menu").hide("slide",{direction:"left"},250).removeClass("active_menu"),$("#small-device-menu-overlay").fadeOut(500),
$("body").removeClass("active_menu_body"))});$("#search_icon").click(function(){$("#small-device-menu").hasClass("active_menu")&&($("#small-device-menu").fadeOut(250).removeClass("active_menu"),$("#small-device-menu-overlay").fadeOut(250));$("#small-device-search").toggle("slide",{direction:"right"},250);$(this).hasClass("icon-search_40")?($(this).removeClass("icon-search_40").addClass("icon-close_40"),$("#small-device-search").addClass("active_search"),$("body").addClass("active_menu_body")):$(this).hasClass("icon-close_40")&&
($(this).addClass("icon-search_40").removeClass("icon-close_40"),$("#small-device-search").removeClass("active_search"),$("body").removeClass("active_menu_body"));$("#menu_close_button").hasClass("icon-close_40")&&($("#menu_close_button").hide(),$("#menu_icon").show())});$("#search-container").click(function(a){a.preventDefault();a.stopPropagation();$(".search-dropdown").hasClass("inactive")&&($(".search-dropdown").velocity("slideDown",{duration:500,complete:function(){$(".search-dropdown").removeClass("inactive").addClass("active");
$(".on-keypress").css({height:$(".on-focus").height()+15+"px"});$(".on-keypress").children(".left-content").css({height:$(".on-keypress").height()+"px"});$(".on-keypress").children(".right-content").css({height:$(".on-keypress").height()+"px"})}}),$("#search-container .icon-down-arrow").addClass("invert"))});$("#search-container-post").click(function(a){a.preventDefault();a.stopPropagation();$(".search-dropdown").hasClass("inactive")&&($(".search-dropdown").velocity("slideDown",{duration:600,complete:function(){$(".search-dropdown").removeClass("inactive").addClass("active");
$(".on-keypress").css({height:$(".on-focus").height()+15+"px"});$(".on-keypress").children(".left-content").css({height:$(".on-keypress").height()+"px"});$(".on-keypress").children(".right-content").css({height:$(".on-keypress").height()+"px"})}}),$("#search-container-post .icon-down-arrow").addClass("invert"))});$(".search-dropdown").click(function(a){a.stopPropagation()});$("#main-search").keypress(function(){$(".on-focus").hasClass("active")&&($(".on-keypress").velocity("fadeIn",{duration:400,
complete:function(){$(".on-keypress").removeClass("inactive").addClass("active")}}),$(".on-focus").removeClass("active").addClass("inactive"),$(".main-search__right-icon").removeClass("icon-down-arrow").removeClass("invert").addClass("icon-close_40"))});$("#search-container .main-search__right-icon").click(function(){$(".on-keypress").hasClass("active")&&$(".search-dropdown").velocity("slideUp",{duration:300,complete:function(){$(".search-dropdown").removeClass("active").addClass("inactive");$(".on-focus").removeClass("inactive").addClass("active");
$(".on-keypress").removeClass("active").addClass("inactive").css({display:"none",opacity:"1"});$("#main-search").val("");$(".main-search__right-icon").addClass("icon-down-arrow").removeClass("icon-close_40")}})});$("#search-container-post .main-search__right-icon").click(function(){$(".on-keypress").hasClass("active")&&$(".search-dropdown").velocity("slideUp",{duration:300,complete:function(){$(".search-dropdown").removeClass("active").addClass("inactive");$(".on-focus").removeClass("inactive").addClass("active");
$(".on-keypress").removeClass("active").addClass("inactive").css({display:"none",opacity:"1"});$("#main-search").val("");$(".main-search__right-icon").addClass("icon-down-arrow").removeClass("icon-close_40")}})});$(document).click(function(a){$(".on-focus").hasClass("active")?$(".search-dropdown").velocity("slideUp",{duration:300,complete:function(){$(".search-dropdown").removeClass("active").addClass("inactive");$(".on-focus").removeClass("inactive").addClass("active");$(".main-search__right-icon").removeClass("invert")}}):
$(".on-keypress").hasClass("active")&&$(".search-dropdown").velocity("slideUp",{duration:300,complete:function(){$(".search-dropdown").removeClass("active").addClass("inactive");$(".main-search__right-icon").removeClass("invert")}})});$("#small-search").keypress(function(a){$(".location-content-small").addClass("inactive").removeClass("active").velocity("fadeOut");var b=$("#small-device-search .search-suggestions");b.hasClass("inactive")&&b.addClass("active").removeClass("inactive").velocity("fadeIn",
{duration:300,complete:function(){b.siblings(".search-categories").css({display:"none"}).addClass("inactive").removeClass("active");$(".search_item .icon-close_40").css({display:"block"})}})});$("#location-small").keypress(function(a){var b=$(".location-content-small");b.hasClass("inactive")&&b.addClass("active").removeClass("inactive").velocity("fadeIn",{duration:300,complete:function(){b.siblings(".search-categories").css({display:"none"}).addClass("inactive").removeClass("active");$(".search_item_l .icon-close_40").css({display:"block"})}})});
$(".search_item .icon-close_40").click(function(){var a=$("#small-device-search .search-suggestions");a.siblings(".search-categories").css({display:"block"}).addClass("active").removeClass("inactive");a.velocity("fadeOut",{duration:300,complete:function(){$(".search_item .icon-close_40").css({display:"none"});a.removeClass("active").addClass("inactive");$("#small-search").val("")}})});$(".main-search__right-icon").click(function(){$(".search-dropdown").hasClass("active")&&$(".search-dropdown").velocity("slideUp",
{duration:300,complete:function(){$(".search-dropdown").removeClass("active").addClass("inactive");$(".main-search__right-icon").removeClass("invert")}})});$("#sign-in-out #in").click(function(){$("#large-overlay #signup-modal").removeClass("active").addClass("unactive");$("#large-overlay #forgot-password-modal").removeClass("active").addClass("unactive");$("body").addClass("restrict-height");$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:200,
complete:function(){$("#large-overlay #login-modal").animate("fadeIn",{duration:400,complete:function(){$("#large-overlay #login-modal").addClass("active").removeClass("unactive")}})}})});$("#login-modal .close-btn").click(function(){$(this).parent().hasClass("active")&&$(this).parent().animate("fadeOut",{duration:200,complete:function(){$(this).removeClass("active").addClass("unactive");$(this).parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").velocity("fadeOut",
{duration:200,complete:function(){$("body").removeClass("restrict-height")}})}})});$("#sign-in-out #up").click(function(){$("#large-overlay #login-modal").removeClass("active").addClass("unactive");$("#large-overlay #forgot-password-modal").removeClass("active").addClass("unactive");$("body").addClass("restrict-height");$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:200,complete:function(){$("#large-overlay #signup-modal").animate("fadeIn",
{duration:200,complete:function(){$("#large-overlay #signup-modal").addClass("active").removeClass("unactive")}})}})});$("#signup-modal .close-btn").click(function(){$(this).parent().hasClass("active")&&$(this).parent().animate("fadeOut",{duration:200,complete:function(){$(this).parent().removeClass("active").addClass("unactive");$(this).parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").velocity("fadeOut",{duration:200,complete:function(){$("body").removeClass("restrict-height")}})}})});
$("#forgot-password-modal .close-btn").click(function(){$(this).parent().hasClass("active")&&$(this).parent().animate("fadeOut",{duration:200,complete:function(){$(this).parent().removeClass("active").addClass("unactive");$(this).parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").velocity("fadeOut",{duration:200,complete:function(){$("body").removeClass("restrict-height")}})}})});$("#login-modal .bottom-strip div:nth-child(2)").click(function(){$("#large-overlay #login-modal").removeClass("active").addClass("unactive");
$("#large-overlay #forgot-password-modal").removeClass("active").addClass("unactive");$("body").addClass("restrict-height");$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:200,complete:function(){$("#large-overlay #signup-modal").animate("fadeIn",{duration:200,complete:function(){$("#large-overlay #signup-modal").addClass("active").removeClass("unactive")}})}})});$("#signup-modal .bottom-strip div:nth-child(2)").click(function(){$("#large-overlay #signup-modal").removeClass("active").addClass("unactive");
$("#large-overlay #forgot-password-modal").removeClass("active").addClass("unactive");$("body").addClass("restrict-height");$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:200,complete:function(){$("#large-overlay #login-modal").animate("fadeIn",{duration:400,complete:function(){$("#large-overlay #login-modal").addClass("active").removeClass("unactive")}})}})});$("#login-modal #forgot").click(function(){$("#large-overlay #login-modal").removeClass("active").addClass("unactive");
$("#large-overlay #signup-modal").removeClass("active").addClass("unactive");$("body").addClass("restrict-height");$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:200,complete:function(){$("#large-overlay #signup-modal").animate("fadeIn",{duration:200,complete:function(){$("#large-overlay #forgot-password-modal").addClass("active").removeClass("unactive")}})}})})});
$(".tabs-bar .nav-tabs li a").on("click",function(){$(".tab-content > .tab-pane").hasClass("active")&&($(".main-container").imagesLoaded(initPackery),$(".tab-click").imagesLoaded(initPackery))});$(".location").keypress(function(){$(".location-content").slideDown()});$(document).click(function(a){$(a.target).closest(".location-content").length?$(".location-content").slideDown():$(".location-content").slideUp()});var myElement=document.querySelector(".nav-container"),headroom=new Headroom(myElement);
headroom.init();jQuery(function(){jQuery.support.placeholder=!1;"placeholder"in document.createElement("input")&&(jQuery.support.placeholder=!0)});
$(function(){if(!$.support.placeholder){var a=document.activeElement;$(":text").focus(function(){""!=$(this).attr("placeholder")&&$(this).val()==$(this).attr("placeholder")&&$(this).val("").removeClass("hasPlaceholder")}).blur(function(){""==$(this).attr("placeholder")||""!=$(this).val()&&$(this).val()!=$(this).attr("placeholder")||$(this).val($(this).attr("placeholder")).addClass("hasPlaceholder")});$(":text").blur();$(a).focus();$("form:eq(0)").submit(function(){$(":text.hasPlaceholder").val("")})}});
function latestFilter(a){"selectDefault"==a?a=selectDefaultFilter:selectDefaultFilter=a;".featured"==a?($(".home").hide(),$(a).show()):".staffpicked"==a||".recommended"==a?($(".home").hide(),$(a).show()):".home"==a?($(".staffpicked").hide(),$(".recommended").hide(),$(".home").show()):".latest"==a&&($(".staffpicked").hide(),$(".recommended").hide(),$(".latest").show());$(".menutab").removeClass("active");$(a+"tab").addClass("active");$container.isotope({filter:a,transitionDuration:"1s",animationEngine:"best-available",
animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}})}function staffPicked(){$.ajax({type:"GET",url:"/application/discovery/featured",success:function(a){$("#loadMorehidden").html(a)}})}function newEvents(){$.ajax({type:"GET",data:"page="+pageCount+"&topic="+topic+"&category="+category+"&city="+city,url:"/application/discovery/new-events",success:function(a){$("#loadMorehidden").html(a)}})}
function loadMoreData(a){1==loadMore&&($("#moreLoader").show(),$.ajax({type:"GET",data:"page="+pageCount+"&topic="+topic+"&category="+category+"&city="+city,url:"/application/discovery/load-more",success:function(a){$("#loadMorehidden").html(a);$("#moreLoader").hide()}}))}function switchTopic(){$("#btn_follow").removeClass("unfollow").addClass("follow");$("#btn_follow").children().empty().addClass("icon-follow-check-white")}function moveToUrl(a){document.location.href=a}var timer;
function autoComplete(a,b,c){""!=a&&1<a.length&&(clearTimeout(timer),timer=setTimeout(function(){""!=a&&0<a.length&&$.ajax({type:"GET",data:"keyword="+a+"&city="+b+"&requestFrom="+c,url:"/application/discovery/auto-search",success:function(a){$(".autosearch").html(a)}})},600))}function autoCityComplete(a){""!=a&&0<a.length&&$.ajax({type:"GET",data:"keyword="+a+"&country="+countrySearch,url:"/application/discovery/cities",success:function(a){$(".autocitysearch").html(a)}})}
function setCity(a){$.ajax({type:"POST",data:"city="+a,url:"/application/discovery/set-city",success:function(a){window.location=a.url}})}
function loadIsoTopeAnimation(){1280<=w?$container=$(".main-container").isotope({itemSelector:".item",layoutMode:"packery",packery:{gutter:30},getSortData:{number:".number parseInt"},transitionDuration:"1s",animationEngine:"best-available",animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}}):480<=w&&1280>w?$container=$(".main-container").isotope({itemSelector:".item",layoutMode:"packery",packery:{gutter:10},getSortData:{number:".number parseInt"},transitionDuration:"1s",
animationEngine:"best-available",animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}}):480>w&&($container=$(".main-container").isotope({itemSelector:".item",layoutMode:"packery",packery:{gutter:5},getSortData:{number:".number parseInt"},transitionDuration:"1s",animationEngine:"best-available",animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}}))}
function filter(a){$container.isotope({filter:a,transitionDuration:"1s",animationEngine:"best-available",animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}})}function sortingData(a){var b=!0;"high"==a&&(b=!1);$container.isotope({getSortData:{number:".number parseInt"},sortBy:"number",sortAscending:{number:b},transitionDuration:"1s",animationEngine:"best-available",animationOptions:{duration:"800"},containerStyle:{position:"relative",overflow:"hidden"}})}
function login(){$("#loggedInUser").addClass("progress-bar progress-bar-striped active");$("#loggedInUser").css("font-size","16px");$("#loginError").hide();$.ajax({type:"POST",data:$("#frmLogin").serialize(),dataType:"json",url:preUrl+"/event/resource/login",success:function(a){1==a.id?("submitEvent"!=postAction&&($("#login-modal").parent().fadeOut(100).removeClass("active").addClass("unactive"),$("#login-modal").parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").fadeOut(100,
function(){$("body").removeClass("restrict-height")})),$("#loginError").html(a.message).show(),""!=postAction&&"follow"==postAction?follow(topicId):""!=postAction&&"likePage"==postAction?likePage():""!=postAction&&"myTicket"==postAction?window.location=accurl+"/account/manage/my-orders":""!=postAction&&"submitEvent"==postAction&&(exchangePage=!0,submitEventExt()),requiredLogin=!0,"submitEvent"!=postAction&&setTimeout(function(){""==postAction&&("home"==pageFromReq?window.location=mainWebUrl+"/home":
location.reload())},200)):$("#loginError").html(a.message).show();$("#loggedInUser").removeClass("progress-bar progress-bar-striped active")}})}
function signUp(){$("#signupUser").addClass("progress-bar progress-bar-striped active");$("#signupUser").css("font-size","16px");$("#signupError").hide();$.ajax({type:"POST",data:$("#frmSignup").serialize()+"&pageUrl="+pageUrl,dataType:"json",url:preUrl+"/event/resource/signup",success:function(a){1==a.id?("submitEvent"!=postAction&&($("#signup-modal").parent().fadeOut(100).removeClass("active").addClass("unactive"),$("#signup-modal").parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").fadeOut(100,
function(){$("body").removeClass("restrict-height")})),$("#signupError").html(a.message).show(),""!=postAction&&"follow"==postAction?follow(topicId):""!=postAction&&"likePage"==postAction?likePage():""!=postAction&&"myTicket"==postAction?window.location=accurl+"/account/manage/my-orders":""!=postAction&&"submitEvent"==postAction&&(exchangePage=!0,submitEventExt()),requiredLogin=!0):$("#signupError").html(a.message).show();$("#signupUser").removeClass("progress-bar progress-bar-striped active")}})}
function submitEventExt(){$("#signup-modal").parent().fadeOut(200).removeClass("active").addClass("unactive");$("#signup-modal").parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").fadeOut(200,function(){$("body").removeClass("restrict-height")});$("#login-modal").parent().fadeOut(200).removeClass("active").addClass("unactive");$("#login-modal").parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").fadeOut(200,function(){$("body").removeClass("restrict-height")});
$("#myModal").modal("show")}
function forgot(){$("#forgotUser").addClass("progress-bar progress-bar-striped active");$("#forgotUser").css("font-size","16px");$("#forgotError").hide();$.ajax({type:"POST",data:$("#frmForgot").serialize(),dataType:"json",url:preUrl+"/event/resource/forgot",success:function(a){1==a.id?($("#forgotError").html(a.message).show(),$("#forgot-password-modal").parent().fadeOut(100).removeClass("active").addClass("unactive"),$("#forgot-password-modal").parents("#large-overlay").removeClass("active-overlay").addClass("unactive-overlay").fadeOut(100,function(){$("body").removeClass("restrict-height")})):
$("#forgotError").html(a.message).show()}})}function followTopic(a){postAction="follow";topicId=a;0==requiredLogin?(preAction="login",$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:100,complete:function(){$("#large-overlay #login-modal").animate("fadeIn",{duration:100,complete:function(){$("#large-overlay #login-modal").addClass("active").removeClass("unactive")}})}})):follow(a)}
function likeIt(a){eventId=a;postAction="likePage";0==requiredLogin?(preAction="login",$("#large-overlay").addClass("active-overlay").removeClass("unactive-overlay").velocity("fadeIn",{duration:100,complete:function(){$("#large-overlay #login-modal").animate("fadeIn",{duration:100,complete:function(){$("#large-overlay #login-modal").addClass("active").removeClass("unactive")}})}})):likePage()}
function likePage(){$.ajax({type:"POST",data:"eventId="+eventId,url:preUrl+"/event/resource/like",success:function(a){""!=preAction&&"login"==preAction?"home"==pageFromReq?window.location=mainWebUrl+"/home":location.reload():($("#likedCount"+eventId).html(a.total),$("#heart div").removeClass("icon-gheart").addClass("icon-heart"))}})}
function follow(a){$.ajax({type:"POST",data:"topic="+a,url:preUrl+"/event/resource/follow",success:function(b){""!=preAction&&"login"==preAction?"home"==pageFromReq?window.location=mainWebUrl+"/home":location.reload():($("#"+a).parent().removeClass("unfollow").addClass("follow"),$("#"+a).children().empty().addClass("icon-follow-check"),$("#btn_follow").removeClass("unfollow").addClass("follow"),$("#btn_follow").children().empty().addClass("icon-follow-check-white"))}})}
function popupShare(a){window.open(a,"","channelmode=0,directories=0,fullscreen=0,location=0,menubar=0,resizable=0,scrollbars=0,status=0,width=600,height=300,top="+Number(screen.height/2-300)+",left="+Number(screen.width/2-300))}function attendees(){$.ajax({type:"POST",data:"eventId="+eventId,url:preUrl+"/event/resource/attendee",success:function(a){$("#attendees").html(a);initPackery()}})}
function youtube(){$.ajax({type:"POST",data:"eventId="+eventId,url:preUrl+"/event/resource/youtube",success:function(a){$("#youtube").html(a)}})}function askOrganizer(){$("#myModal").modal("show")}
function sendQuery(){if(validateAskOrganiser()){$("#alertmsg").hide();$("#progressBarOrg").show();var a=$("#frmOrgQuery").serialize();$.ajax({type:"POST",dataType:"json",url:preUrl+"/event/index/send-query",data:a,success:function(a){$("#progressBarOrg").hide();"1"==a.id&&($("#orgName").val(""),$("#orgEmailId").val(""),$("#orgPhoneNo").val(""),$("#orgComment").val(""));$("#alertmsg").html(a.message);$("#alertmsg").show();setTimeout(function(){$("#alertmsg").hide();$("#myModal").modal("hide")},2E3)}})}}
function validateAskOrganiser(){var a=$("#orgName").val(),b=$("#orgEmailId").val(),c=$("#orgPhoneNo").val(),d=$("#orgComment").val();if(""==a.trim()||"Enter Your Name"==a)return $("#alertmsg").html("Name is Required."),$("#alertmsg").show(),!1;if(""==b||"Enter Your Email id"==b)return $("#alertmsg").html("Email Id is Required."),$("#alertmsg").show(),!1;if(IsEmail(b)){if(""==c.trim()||"Enter Your Phone No"==c)return $("#alertmsg").html("Phone No is Required."),$("#alertmsg").show(),!1;if(""==d.trim())return $("#alertmsg").html("Query is Required."),
$("#alertmsg").show(),!1}else return $("#alertmsg").html("Valid Email Id Required."),$("#alertmsg").show(),!1;return!0}function IsEmail(a){return/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(a)}
function saveSubscriberDetails(){$("#error_sub").show();var a=$("#frmSubscribe").serialize();$.ajax({type:"POST",url:"/application/discovery/save-subscriber-details",data:a+"&pageUrl="+pageUrl,dataType:"json",success:function(a){"0"==a.id?$("#error_sub").html(a.message).show():$("#sub-news-div").html("<h3>"+a.message+"</h3>")}});return!1}
(function(a){a.oauthpopup=function(a){a.windowName=a.windowName||"ConnectWithOAuth";a.windowOptions=a.windowOptions||"location=0,status=0,width="+a.width+",height="+a.height+",scrollbars=1,left=400,top=250";a.callback=a.callback||function(){window.location.reload()};var c=this;c._oauthWindow=window.open(a.path,a.windowName,a.windowOptions);c._oauthInterval=window.setInterval(function(){c._oauthWindow.closed&&(window.clearInterval(c._oauthInterval),a.callback())},1E3)}})(jQuery);
 $('#small-device-menu-overlay').click(function() {
        $('#menu_close_button').hide();
        $('#menu_icon').show();
});
